name: First Interaction

on:
  pull_request:
  issues:
    types: opened

concurrency:
  group: {{ '${{github.workflow}}' }}-{{ '${{github.ref}}' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: {{ '${{ secrets.GITHUB_TOKEN }}' }}
          issue-message: "Thank you for opening this ISSUE. We'll give you a return ASAP ğŸ‘"
          pr-message: "Thank you for your contribution. We'll give you a return ASAP ğŸ‘"